---
- name: Install Kubernetes components
  become: true
  block:
    - name: Download Kubernetes GPG key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"
    - name: Add Kubernetes repository to apt sources
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
        state: present
    - name: Install Kubernetes packages
      ansible.builtin.apt:
        pkg:
          - kubeadm
          - kubelet
          - kubectl
        state: present
    - name: Start the kubelet on all nodes
      ansible.builtin.service:
        name: kubelet
        enabled: true
        state: started
    - name: Copy Kubeadm config for cgroup driver
      ansible.builtin.copy:
        src: ./files/ka_config.yaml
        dest: "{{ ansible_user_dir }}/ka-config.yaml"
        mode: "0744"
    # if your node has a swap partition, turn it off - required by the kubelet
    #
    # - name: Disabling swap
    #   ansible.builtin.shell:
    #     cmd: |
    #       swapoff -a
