---
- name: Setup apt and install system requirements for Docker
  become: true
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install general requirements
      ansible.builtin.apt:
        pkg:
          - curl
          - gnupg
          - ca-certificates
        state: present
    - name: Create keyrings folder
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
    - name: Add official Docker apt-key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
    - name: Know the node architecture
      ansible.builtin.shell:
        cmd: dpkg --print-architecture
      register: node_architecure
    - name: Add Docker repository to apt sources
      ansible.builtin.apt_repository:
        repo: deb [arch={{ node_architecure.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable | tee /etc/apt/sources.list.d/docker.list > /dev/null
        state: present
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install required Docker packages
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
    - name: Add vagrant user to Docker group
      ansible.builtin.user:
        name: vagrant
        append: true
        groups:
          - "docker"
    - name: Enable containerd CRI plugin
      ansible.builtin.copy:
        src: ./files/containerd_config.toml
        dest: /etc/containerd/config.toml
        mode: "0644"
    - name: Restart the containerd service
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: true
